### ISSUE TITLE
关于求转移概率得分

### ISSUE THREAD

**Issue by babyhuzi111** [bojone/crf#1]
您好，我在看到您实现crf的时候，转移概率是通过两个错位的labels相乘得到，这一点我不是特别理解，如果label是one-hot向量，两个错位的label相乘的结果应该全为0了？用numpy模拟了一下确实结果为0，希望能予以解答。

**Comment by bojone** [comment]
```
        labels1 = K.expand_dims(labels[:, :-1], 3)
        labels2 = K.expand_dims(labels[:, 1:], 2)
        labels = labels1 * labels2 # 两个错位labels，负责从转移矩阵中抽取目标转移得分
        trans = K.expand_dims(K.expand_dims(self.trans, 0), 0)
        trans_score = K.sum(K.sum(trans*labels, [2,3]), 1, keepdims=True)
```
你说的是这几行？
labels1和labels2已经expand_dims了，你可以认为原来labels1,labels2都是一个向量，但是labels1 * labels2已经是一个矩阵了，这个矩阵是原来向量任意两个数的乘积（两两组合）。

**Comment by babyhuzi111** [comment]
import numpy as np
x1 = np.array([[1,0],[0,0],[0,1]])
x2 = np.array([[0,0],[0,1],[1,0]])
y1 = np.expand_dims(x1, 3)
y2 = np.expand_dims(x2, 2)
y3 = y1*y2
print(y3)
我是这样模拟的，不知道对不对，x1是序列的第1,2个标签，x2是序列2,3个标签。

**Comment by bojone** [comment]
当然不对呀。x1和x2都是三维的...shape = (batch_size, seq_len, num_labels)
