### ISSUE TITLE
如何观察loss函数里的变量？

### ISSUE THREAD

**Issue by hnyz979** [bojone/crf#2]
您好，首先感谢您的分享。
我对CRF了解不多，想用您提供的语料分析的例子，观察一下CRF的执行过程。然后我发现在crf_keras.py文件中，有一个loss函数和一个accuracy函数，然后我希望能够像在tensorflow中那样，获取这两个函数中的每一个变量，然后sess.run掉，观察其中的内容。但是我对Keras不是很熟悉，请问是否可以获取loss函数或者accuracy函数中的变量（如loss函数中的init_states），观察其内容？

PS：网上说过获取keras模型中间层输出的方法，如https://blog.csdn.net/u010420283/article/details/80303231，但难点是您程序里的init_states等变量似乎并不是keras模型里的变量，所以这种方法似乎不能解决这个问题。

多谢指点！

**Comment by bojone** [comment]
标量函数可以直接作为metrics添加到输出显示中。

**Comment by HornGate** [comment]
苏神，您好！请问这个CRF层，可以用来作为图像分割的最后一层吗？

**Comment by bojone** [comment]
@HornGate 我不知道crf在图像分割是怎么用的，没法提供意见

**Comment by bojone** [comment]
@hnyz979 
https://kexue.fm/archives/6575#K.function%EF%BC%81
