### ISSUE TITLE
可以设定自动忽略所有 padding 的 0 么

### ISSUE THREAD

**Issue by BrikerMan** [bojone/crf#4]
如题，因为通常序列会在后面补一定数量的 0， 能忽略这个么？

**Comment by bojone** [comment]
有mask机制，方法是在原来的标注数目上加一个标签，比如原来是sbme的4tags分词，你就改为5tags，第五个tag用来标记padding部分，然后用crf层的时候设置ignore_last_label=True就行了。

具体的例子在 https://github.com/bojone/crf/blob/master/word_seg.py

**Comment by BrikerMan** [comment]
谢谢，有打算发布到 pypi 的计划么？

**Comment by BrikerMan** [comment]
> 有mask机制，方法是在原来的标注数目上加一个标签，比如原来是sbme的4tags分词，你就改为5tags，第五个tag用来标记padding部分，然后用crf层的时候设置ignore_last_label=True就行了。
> 
> 具体的例子在 https://github.com/bojone/crf/blob/master/word_seg.py

这个方法保存再加载会出错。
