### ISSUE TITLE
请问为什么要在K.rnn的Init_states外面包一层[]？

### ISSUE THREAD

**Issue by xsthunder** [bojone/crf#9]
苏神你好，

init_state包一层
https://github.com/bojone/crf/blob/6bd55d9136d9430cf4c04cfee3c1b288dbe01628/crf_keras.py#L61

step_function

里面解开
https://github.com/bojone/crf/blob/6bd55d9136d9430cf4c04cfee3c1b288dbe01628/crf_keras.py#L31

作为新状态又包一层
https://github.com/bojone/crf/blob/6bd55d9136d9430cf4c04cfee3c1b288dbe01628/crf_keras.py#L36

[根据文档](https://www.tensorflow.org/api_docs/python/tf/keras/backend/rnn)对initial_states的定义
initial_states: Tensor with shape (samples, state_size) (no time dimension), containing the initial values for the states used in the step function. In the case that state_size is in a nested shape, the shape of initial_states will also follow the nested structure.

但这里的`initial_state.shape=(1,samples, state_size)`的这个是有特殊考虑吗？

**Comment by bojone** [comment]
Keras就是这样设计的...

**Comment by xsthunder** [comment]
文档是这样说的
https://www.tensorflow.org/api_docs/python/tf/keras/backend/rnn
initial_states: Tensor with shape (samples, state_size) 
可能是版本不一样吧，谢谢回答
